name: Deploy to EC2

on:
  push:
    branches:
      - main   # deploy only when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # # 1. Checkout Code (required before anything else)
      # - name: Checkout Repository
      #   uses: actions/checkout@v4

      # 2. Connect to EC2 via SSH and run commands on EC2ssd
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}         # example: 13.232.1.113
          username: ${{ secrets.EC2_USERNAME }} # example: ubuntu
          key: ${{ secrets.EC2_KEY }}   # private key content
          script: |
            echo "=== CURRENT DIRECTORY ==="
            pwd
            echo "=== LIST FILES ==="
            ls -la
            echo "=== LOOKING FOR deploy.sh ==="
            find / -maxdepth 4 -name "deploy.sh" 2>/dev/null
